services:
  web:
    build:
      context: ./web
    container_name: web
    ports:
      - "3000:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/home/bun/data
      - ./data/config:/home/bun/data/config
      - ./web:/usr/src/app/
    environment:
      - LOG_LEVEL=info # valid options: (undefined) | info | debug | warning | error | fatal
      - BETTER_AUTH_SECRET=ngJuz7MgddaJTjcMpUbdPLEYGjvattDaAVoe4CFbHsrT34hL
      - SOCKET_PATH=/home/bun/data/config/api.sock
    command: ["./startup-debug.sh"]
    healthcheck:
      test: curl --fail https://web.copima.orb.local/api/admin/health || exit 1
      interval: 3s
      retries: 100
      start_period: 3s
      timeout: 5s
  
  crawler:
    build:
      context: ./crawler
    container_name: crawler
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/home/bun/data
      - ./data/config:/home/bun/data/config
      - ./crawler:/usr/src/app/
    environment:
      - LOG_LEVEL=debug # valid options: (undefined) | info | debug | warning | error | fatal
      - DEBUG=true
      - CRAWLER_MODE=socket
      - SOCKET_PATH=/home/bun/data/config/api.sock
      - CRAWLER_DATA_ROOT_DIR=/home/bun/data/archive
      - CRAWLER_ID_DATABASE_PATH=/home/bun/data/id_database.db
      - CRAWLER_MAX_CONCURRENT_TASKS=3
      - CRAWLER_IDLE_POLL_INTERVAL_SECONDS=20
      - CRAWLER_TASK_QUEUE_URL=unix:/home/bun/data/config/api.sock:/api/internal/jobs/open
      - CRAWLER_PROGRESS_API_ENDPOINT=unix:/home/bun/data/config/api.sock:/api/internal/jobs/progress
      - CRAWLER_TOKEN_REFRESH_API_ENDPOINT=unix:/home/bun/data/config/api.sock:/api/internal/refresh-token
      - CRAWLER_HASHING_SECRET_KEY=1234567890123456789012345678901234567890123456789012345678901234
      - CRAWLER_HASHING_ALGORITHM=sha256
    entrypoint: ["./startup-debug.sh"]
#    depends_on:
#      web:
#        condition: service_healthy
      