services:
  surveytool:
    container_name: surveytool
    #    image: phennel/copilot-study:latest
    build: .
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /mnt/data:/home/bun/data # This is the main storage location, which should be mirrored to / mounted from a persistent volume
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT="HOST/api/project" # to keep tabs on the crawler, it loggs to a self-hosted openobserve instance in Bremen
      - OTEL_EXPORTER_OTLP_HEADERS="Authorization=Basic " # !!!! OPEN OBSERVE TOKEN !!!!
      - OTEL_EXPORTER_OTLP_PROTOCOL="http/json"
      - LOG_LEVEL=info
#      - AUTORESTIC_STORAGEBOX_RESTIC_PASSWORD= # !!! ENCRYPTION KEY FOR BACKUP !!!
#      - BACKUP_USER= # !!! USER FOR BACKUP SERVICE !!!
#      - BACKUP_PRIVATE_KEY= # !!! SSH PRIVATE KEY FPR BACKUP SERVICE !!!
